# Generated by Django 2.2.7 on 2019-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191207_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='appointment_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
