# Generated by Django 2.2.7 on 2019-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_visitor1'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor1',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
