# Generated by Django 2.2.7 on 2019-12-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_visitor1_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, help_text='上传相应的图片。', null=True, upload_to='', verbose_name='picture'),
        ),
    ]
