# Generated by Django 2.2.7 on 2019-12-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, help_text='上传相应的图片。', null=True, upload_to='BookImage', verbose_name='picture'),
        ),
    ]
