# Generated by Django 2.2.7 on 2019-12-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191230_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, default='BookImage/404.png', help_text='上传相应的图片。', null=True, upload_to='BookImage', verbose_name='picture'),
        ),
    ]
