# Generated by Django 2.2.7 on 2019-12-30 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20191230_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='通知的标题', max_length=20, null=True, verbose_name='标题')),
                ('info', models.CharField(blank=True, help_text='通知的内容', max_length=200, null=True, verbose_name='通知')),
                ('Release_time', models.DateField(blank=True, default=datetime.date.today, help_text='时间格式：2019/12/11', null=True, verbose_name='发布时间')),
            ],
            options={
                'ordering': ['Release_time'],
            },
        ),
    ]
