# Generated by Django 2.2.7 on 2019-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='info',
            field=models.TextField(blank=True, help_text='通知的内容', max_length=200, null=True, verbose_name='通知'),
        ),
    ]
